// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojo.Utils;

#nullable disable

namespace TPDojo.Migrations
{
    [DbContext(typeof(DojoContext))]
    [Migration("20230822132329_SamouraiDataInsert")]
    partial class SamouraiDataInsert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourais");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Force = 755,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1298,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1120,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 103,
                            Force = 1160,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1987,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 105,
                            Force = 1367,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 106,
                            Force = 1293,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1015,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 108,
                            Force = 372,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1624,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 110,
                            Force = 352,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 111,
                            Force = 156,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 112,
                            Force = 395,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1460,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 114,
                            Force = 1514,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 115,
                            Force = 431,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 116,
                            Force = 841,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 117,
                            Force = 1280,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 118,
                            Force = 5,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 119,
                            Force = 755,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1431,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 121,
                            Force = 410,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 122,
                            Force = 605,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 123,
                            Force = 603,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1717,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 125,
                            Force = 1843,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 126,
                            Force = 115,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1784,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 128,
                            Force = 1620,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 129,
                            Force = 1465,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 130,
                            Force = 290,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 131,
                            Force = 492,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 132,
                            Force = 497,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 133,
                            Force = 1586,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 134,
                            Force = 1686,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 135,
                            Force = 20,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1893,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 137,
                            Force = 694,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1648,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 139,
                            Force = 511,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1523,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 141,
                            Force = 1227,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 142,
                            Force = 777,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 143,
                            Force = 812,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1923,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 145,
                            Force = 1908,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 146,
                            Force = 1324,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 147,
                            Force = 1305,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 148,
                            Force = 408,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 149,
                            Force = 895,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 150,
                            Force = 1132,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1929,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 152,
                            Force = 403,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 153,
                            Force = 277,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 154,
                            Force = 1606,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 155,
                            Force = 1755,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 156,
                            Force = 861,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 157,
                            Force = 1110,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1118,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 159,
                            Force = 87,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 160,
                            Force = 1585,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1688,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 162,
                            Force = 1881,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1257,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1079,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 165,
                            Force = 295,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 166,
                            Force = 1567,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1070,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1871,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 169,
                            Force = 1347,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1824,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1203,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 172,
                            Force = 216,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 173,
                            Force = 224,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 174,
                            Force = 153,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1884,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 176,
                            Force = 3,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 177,
                            Force = 206,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 178,
                            Force = 398,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 179,
                            Force = 1176,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 180,
                            Force = 514,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1296,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1785,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 183,
                            Force = 1881,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 184,
                            Force = 1953,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 185,
                            Force = 1605,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 186,
                            Force = 910,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 187,
                            Force = 880,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1988,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 189,
                            Force = 1055,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 190,
                            Force = 444,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1586,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 192,
                            Force = 271,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 1137,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 194,
                            Force = 284,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 195,
                            Force = 1027,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 196,
                            Force = 1323,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 197,
                            Force = 183,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1313,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 199,
                            Force = 808,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1010,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 201,
                            Force = 1243,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 202,
                            Force = 494,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1493,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 204,
                            Force = 171,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 205,
                            Force = 1885,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 206,
                            Force = 777,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 207,
                            Force = 1972,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1969,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 209,
                            Force = 19,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 210,
                            Force = 463,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1125,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1582,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 213,
                            Force = 1750,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 214,
                            Force = 805,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 215,
                            Force = 804,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 216,
                            Force = 1240,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 217,
                            Force = 1640,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 218,
                            Force = 363,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 219,
                            Force = 141,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 220,
                            Force = 1158,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 221,
                            Force = 568,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1548,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 223,
                            Force = 306,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 224,
                            Force = 710,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 225,
                            Force = 223,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 226,
                            Force = 1678,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 227,
                            Force = 1279,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 228,
                            Force = 532,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 229,
                            Force = 146,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1194,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 543,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 232,
                            Force = 1545,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 233,
                            Force = 219,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 234,
                            Force = 510,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 235,
                            Force = 20,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 236,
                            Force = 1326,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1076,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1478,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1202,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 240,
                            Force = 27,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 241,
                            Force = 737,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 242,
                            Force = 1742,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1004,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 244,
                            Force = 828,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 245,
                            Force = 715,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 246,
                            Force = 1530,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 247,
                            Force = 133,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1470,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1180,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 250,
                            Force = 333,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 251,
                            Force = 802,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 252,
                            Force = 325,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 253,
                            Force = 342,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 254,
                            Force = 863,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 255,
                            Force = 85,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 256,
                            Force = 1001,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 257,
                            Force = 411,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 628,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 259,
                            Force = 297,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 260,
                            Force = 511,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1118,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 262,
                            Force = 62,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 263,
                            Force = 220,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 264,
                            Force = 1577,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 265,
                            Force = 1280,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1605,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 267,
                            Force = 1776,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 268,
                            Force = 1543,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 269,
                            Force = 1514,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1293,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1695,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1432,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 1895,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 274,
                            Force = 561,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1937,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1052,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1259,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 278,
                            Force = 1609,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1704,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 280,
                            Force = 130,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1015,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 282,
                            Force = 938,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 283,
                            Force = 1261,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1260,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 285,
                            Force = 421,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1393,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1517,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1662,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 289,
                            Force = 549,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 290,
                            Force = 1116,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 291,
                            Force = 129,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 292,
                            Force = 397,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 293,
                            Force = 330,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 294,
                            Force = 826,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 295,
                            Force = 1253,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 296,
                            Force = 1679,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1980,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 879,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1284,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1100,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 301,
                            Force = 751,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 302,
                            Force = 962,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 303,
                            Force = 309,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 304,
                            Force = 597,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1541,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 306,
                            Force = 604,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 307,
                            Force = 828,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 308,
                            Force = 219,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 309,
                            Force = 820,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 310,
                            Force = 1575,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 311,
                            Force = 1479,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 312,
                            Force = 1848,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 313,
                            Force = 40,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 235,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1648,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1948,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 317,
                            Force = 120,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 1829,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 1771,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 320,
                            Force = 714,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 321,
                            Force = 117,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 322,
                            Force = 1134,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 323,
                            Force = 150,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 324,
                            Force = 787,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 325,
                            Force = 148,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 326,
                            Force = 34,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 327,
                            Force = 940,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 328,
                            Force = 1742,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 329,
                            Force = 1446,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 330,
                            Force = 150,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 331,
                            Force = 549,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 332,
                            Force = 1795,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 333,
                            Force = 931,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 334,
                            Force = 533,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 335,
                            Force = 566,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 336,
                            Force = 1830,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 337,
                            Force = 1715,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 338,
                            Force = 1690,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 339,
                            Force = 1965,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 340,
                            Force = 711,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 341,
                            Force = 754,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 342,
                            Force = 242,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 343,
                            Force = 167,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 344,
                            Force = 1837,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 345,
                            Force = 1017,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 346,
                            Force = 649,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 347,
                            Force = 30,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 348,
                            Force = 824,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 349,
                            Force = 805,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 350,
                            Force = 1307,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 351,
                            Force = 943,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 352,
                            Force = 1231,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 353,
                            Force = 1024,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 354,
                            Force = 1450,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 355,
                            Force = 1590,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 356,
                            Force = 1220,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 357,
                            Force = 1573,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 358,
                            Force = 571,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 359,
                            Force = 527,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 360,
                            Force = 481,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 361,
                            Force = 646,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 362,
                            Force = 1869,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 363,
                            Force = 1095,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 364,
                            Force = 855,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 365,
                            Force = 55,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 366,
                            Force = 1574,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 367,
                            Force = 1030,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 368,
                            Force = 702,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 369,
                            Force = 238,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 370,
                            Force = 1976,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 371,
                            Force = 1966,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 372,
                            Force = 1937,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 373,
                            Force = 397,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 374,
                            Force = 583,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 375,
                            Force = 184,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 376,
                            Force = 1234,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 377,
                            Force = 1303,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 378,
                            Force = 1375,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 379,
                            Force = 1305,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 380,
                            Force = 320,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 381,
                            Force = 61,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 382,
                            Force = 1883,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 383,
                            Force = 206,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 384,
                            Force = 970,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 385,
                            Force = 520,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 386,
                            Force = 1737,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 387,
                            Force = 1185,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 388,
                            Force = 1855,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 389,
                            Force = 28,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 390,
                            Force = 1059,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 391,
                            Force = 1748,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 392,
                            Force = 832,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 393,
                            Force = 991,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 394,
                            Force = 419,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 395,
                            Force = 153,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 396,
                            Force = 1399,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 397,
                            Force = 192,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 398,
                            Force = 1539,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 399,
                            Force = 516,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 400,
                            Force = 1057,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 401,
                            Force = 1054,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 402,
                            Force = 1587,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 403,
                            Force = 624,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 404,
                            Force = 351,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 405,
                            Force = 1343,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 406,
                            Force = 453,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 407,
                            Force = 937,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 408,
                            Force = 979,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 409,
                            Force = 902,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 410,
                            Force = 656,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 411,
                            Force = 1723,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 412,
                            Force = 1354,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 413,
                            Force = 1967,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 414,
                            Force = 143,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 415,
                            Force = 1576,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 416,
                            Force = 1741,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 417,
                            Force = 699,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 418,
                            Force = 407,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 419,
                            Force = 1069,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
