// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojo.Utils;

#nullable disable

namespace TPDojo.Migrations
{
    [DbContext(typeof(DojoContext))]
    [Migration("20230823092205_ArtsMartiaux")]
    partial class ArtsMartiaux
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.Property<int>("ArtsMartiauxId")
                        .HasColumnType("int");

                    b.Property<int>("SamouraisId")
                        .HasColumnType("int");

                    b.HasKey("ArtsMartiauxId", "SamouraisId");

                    b.HasIndex("SamouraisId");

                    b.ToTable("ArtMartialSamourai");
                });

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtsMartiaux");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourais");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Force = 851,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1495,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1079,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 103,
                            Force = 619,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1088,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 105,
                            Force = 1739,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 106,
                            Force = 424,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1372,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 108,
                            Force = 827,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 109,
                            Force = 214,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 110,
                            Force = 784,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 111,
                            Force = 457,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 112,
                            Force = 247,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 114,
                            Force = 1284,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1030,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 116,
                            Force = 958,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 117,
                            Force = 45,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1325,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 119,
                            Force = 742,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 120,
                            Force = 187,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 121,
                            Force = 1341,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 122,
                            Force = 1043,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 123,
                            Force = 695,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 124,
                            Force = 29,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 125,
                            Force = 313,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 126,
                            Force = 483,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1064,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 128,
                            Force = 398,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 129,
                            Force = 1573,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 130,
                            Force = 293,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 131,
                            Force = 1768,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 132,
                            Force = 715,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 133,
                            Force = 581,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 134,
                            Force = 626,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 135,
                            Force = 1081,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1981,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 137,
                            Force = 118,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1615,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 139,
                            Force = 1093,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1676,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 141,
                            Force = 494,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 142,
                            Force = 1982,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 143,
                            Force = 348,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1979,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 145,
                            Force = 1666,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 146,
                            Force = 1825,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 147,
                            Force = 1142,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 148,
                            Force = 233,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 149,
                            Force = 942,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 150,
                            Force = 1673,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1923,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 152,
                            Force = 1462,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1795,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 154,
                            Force = 434,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 155,
                            Force = 1537,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 156,
                            Force = 68,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 157,
                            Force = 248,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1562,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 159,
                            Force = 1340,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 160,
                            Force = 927,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 355,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 162,
                            Force = 712,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1575,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1485,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 165,
                            Force = 1618,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 166,
                            Force = 799,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1739,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1548,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 169,
                            Force = 1932,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1195,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 171,
                            Force = 838,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 172,
                            Force = 1140,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1249,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 174,
                            Force = 1675,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 175,
                            Force = 325,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 176,
                            Force = 500,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 177,
                            Force = 577,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 178,
                            Force = 649,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 179,
                            Force = 518,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 180,
                            Force = 1576,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1919,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 182,
                            Force = 845,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 183,
                            Force = 156,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 184,
                            Force = 845,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 185,
                            Force = 1097,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 186,
                            Force = 0,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 187,
                            Force = 136,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1289,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 189,
                            Force = 830,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 190,
                            Force = 771,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 191,
                            Force = 27,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 192,
                            Force = 1098,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 1961,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 194,
                            Force = 712,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 195,
                            Force = 174,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 196,
                            Force = 1622,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 197,
                            Force = 1481,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1826,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 199,
                            Force = 1024,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1621,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 201,
                            Force = 136,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 202,
                            Force = 809,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1140,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 204,
                            Force = 656,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 205,
                            Force = 779,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 206,
                            Force = 223,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 207,
                            Force = 268,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1850,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 209,
                            Force = 603,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 210,
                            Force = 138,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 211,
                            Force = 135,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1348,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 213,
                            Force = 80,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 214,
                            Force = 539,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 215,
                            Force = 1770,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 216,
                            Force = 1558,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 217,
                            Force = 1466,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 218,
                            Force = 1767,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 219,
                            Force = 173,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 220,
                            Force = 1365,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 221,
                            Force = 1520,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1864,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 223,
                            Force = 1572,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 224,
                            Force = 575,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 225,
                            Force = 88,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 226,
                            Force = 776,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 227,
                            Force = 1987,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 228,
                            Force = 1920,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 229,
                            Force = 928,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 230,
                            Force = 314,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 1785,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 232,
                            Force = 616,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 233,
                            Force = 1429,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1591,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 235,
                            Force = 1891,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 236,
                            Force = 1903,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 237,
                            Force = 116,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 238,
                            Force = 811,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1265,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 240,
                            Force = 142,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 241,
                            Force = 1372,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 242,
                            Force = 561,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 243,
                            Force = 12,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 244,
                            Force = 1445,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 245,
                            Force = 167,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 246,
                            Force = 1713,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 247,
                            Force = 1028,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 248,
                            Force = 884,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1432,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 250,
                            Force = 879,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1487,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 252,
                            Force = 659,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 253,
                            Force = 650,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1091,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1567,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 256,
                            Force = 1251,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1132,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 458,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 259,
                            Force = 1949,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1585,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 455,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 262,
                            Force = 799,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 263,
                            Force = 664,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 264,
                            Force = 1429,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 265,
                            Force = 10,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 266,
                            Force = 630,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 267,
                            Force = 1293,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 268,
                            Force = 1269,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 269,
                            Force = 69,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 270,
                            Force = 765,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 271,
                            Force = 944,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1657,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 596,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1735,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 275,
                            Force = 795,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1311,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 277,
                            Force = 108,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 278,
                            Force = 1080,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 279,
                            Force = 906,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 280,
                            Force = 565,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1698,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 282,
                            Force = 1048,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 283,
                            Force = 1794,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 284,
                            Force = 606,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 285,
                            Force = 577,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1875,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 287,
                            Force = 20,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1113,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 289,
                            Force = 749,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 290,
                            Force = 6,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 291,
                            Force = 455,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 292,
                            Force = 1372,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 293,
                            Force = 598,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 294,
                            Force = 684,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 295,
                            Force = 603,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 296,
                            Force = 619,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1522,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 481,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1752,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 528,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 301,
                            Force = 613,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1079,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 303,
                            Force = 66,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 304,
                            Force = 57,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 305,
                            Force = 180,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 306,
                            Force = 242,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 307,
                            Force = 11,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 308,
                            Force = 980,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1517,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 310,
                            Force = 7,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 311,
                            Force = 26,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 312,
                            Force = 360,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 313,
                            Force = 757,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 1524,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1147,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 316,
                            Force = 573,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1566,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 1136,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 235,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 320,
                            Force = 1211,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 321,
                            Force = 1240,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 322,
                            Force = 1727,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 323,
                            Force = 492,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 324,
                            Force = 932,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 325,
                            Force = 836,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 326,
                            Force = 188,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 327,
                            Force = 1465,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 328,
                            Force = 39,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 329,
                            Force = 639,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 330,
                            Force = 1908,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 331,
                            Force = 1091,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 332,
                            Force = 536,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 333,
                            Force = 639,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 334,
                            Force = 495,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 335,
                            Force = 524,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 336,
                            Force = 932,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 337,
                            Force = 1409,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 338,
                            Force = 95,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 339,
                            Force = 1877,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 340,
                            Force = 1246,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 341,
                            Force = 299,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 342,
                            Force = 792,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 343,
                            Force = 1241,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 344,
                            Force = 1668,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 345,
                            Force = 160,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 346,
                            Force = 583,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 347,
                            Force = 811,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 348,
                            Force = 1957,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 349,
                            Force = 1422,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 350,
                            Force = 1620,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 351,
                            Force = 581,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 352,
                            Force = 1910,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 353,
                            Force = 123,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 354,
                            Force = 1272,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 355,
                            Force = 1187,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 356,
                            Force = 1087,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 357,
                            Force = 243,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 358,
                            Force = 406,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 359,
                            Force = 1718,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 360,
                            Force = 1271,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 361,
                            Force = 367,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 362,
                            Force = 647,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 363,
                            Force = 944,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 364,
                            Force = 1393,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 365,
                            Force = 1346,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 366,
                            Force = 1458,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 367,
                            Force = 467,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 368,
                            Force = 375,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 369,
                            Force = 1405,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 370,
                            Force = 39,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 371,
                            Force = 1365,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 372,
                            Force = 1781,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 373,
                            Force = 1658,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 374,
                            Force = 219,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 375,
                            Force = 1121,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 376,
                            Force = 1338,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 377,
                            Force = 55,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 378,
                            Force = 1412,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 379,
                            Force = 1527,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 380,
                            Force = 1460,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 381,
                            Force = 1060,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 382,
                            Force = 734,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 383,
                            Force = 669,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 384,
                            Force = 226,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 385,
                            Force = 1387,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 386,
                            Force = 1396,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 387,
                            Force = 961,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 388,
                            Force = 992,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 389,
                            Force = 1233,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 390,
                            Force = 1745,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 391,
                            Force = 1858,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 392,
                            Force = 1436,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 393,
                            Force = 1295,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 394,
                            Force = 1386,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 395,
                            Force = 1036,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 396,
                            Force = 1765,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 397,
                            Force = 1464,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 398,
                            Force = 747,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 399,
                            Force = 952,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 400,
                            Force = 1734,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 401,
                            Force = 891,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 402,
                            Force = 1725,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 403,
                            Force = 1186,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 404,
                            Force = 1622,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 405,
                            Force = 1558,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 406,
                            Force = 1056,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 407,
                            Force = 440,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 408,
                            Force = 1854,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 409,
                            Force = 395,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 410,
                            Force = 1161,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 411,
                            Force = 1401,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 412,
                            Force = 567,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 413,
                            Force = 509,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 414,
                            Force = 1115,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 415,
                            Force = 1184,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 416,
                            Force = 1735,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 417,
                            Force = 953,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 418,
                            Force = 1680,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 419,
                            Force = 404,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.HasOne("BO.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("ArtsMartiauxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.Samourai", null)
                        .WithMany()
                        .HasForeignKey("SamouraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
