// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojoAPI.Utils;

#nullable disable

namespace TPDojoAPI.Migrations
{
    [DbContext(typeof(DojoAPIContext))]
    [Migration("20230823142011_WebAppToAPIMigration")]
    partial class WebAppToAPIMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.Property<int>("ArtsMartiauxId")
                        .HasColumnType("int");

                    b.Property<int>("SamouraisId")
                        .HasColumnType("int");

                    b.HasKey("ArtsMartiauxId", "SamouraisId");

                    b.HasIndex("SamouraisId");

                    b.ToTable("ArtMartialSamourai");
                });

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtsMartiaux");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourais");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Force = 500,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1043,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1627,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 103,
                            Force = 1963,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1490,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 105,
                            Force = 396,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 106,
                            Force = 519,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1340,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 108,
                            Force = 252,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1656,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 110,
                            Force = 185,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 111,
                            Force = 1133,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 112,
                            Force = 190,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 113,
                            Force = 142,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 114,
                            Force = 1596,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 115,
                            Force = 12,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 116,
                            Force = 851,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 117,
                            Force = 1327,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1352,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 119,
                            Force = 87,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1671,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 121,
                            Force = 1279,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 122,
                            Force = 51,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 123,
                            Force = 923,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1311,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 125,
                            Force = 223,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 126,
                            Force = 320,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1455,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 128,
                            Force = 1801,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 129,
                            Force = 1649,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 130,
                            Force = 1224,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 131,
                            Force = 1183,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 132,
                            Force = 714,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 133,
                            Force = 976,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 134,
                            Force = 542,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 135,
                            Force = 1725,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1335,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 137,
                            Force = 200,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1166,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 139,
                            Force = 1603,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1847,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 141,
                            Force = 1429,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 142,
                            Force = 832,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1753,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1388,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 145,
                            Force = 512,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 146,
                            Force = 1805,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 147,
                            Force = 544,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 148,
                            Force = 314,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 149,
                            Force = 820,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 150,
                            Force = 283,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 151,
                            Force = 156,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 152,
                            Force = 563,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 153,
                            Force = 175,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 154,
                            Force = 1294,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 155,
                            Force = 594,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 156,
                            Force = 524,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 157,
                            Force = 23,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 28,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 159,
                            Force = 1577,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 160,
                            Force = 990,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 718,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 162,
                            Force = 1289,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 163,
                            Force = 392,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1427,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 165,
                            Force = 1449,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 166,
                            Force = 1994,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 167,
                            Force = 783,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 168,
                            Force = 776,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 169,
                            Force = 23,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 170,
                            Force = 340,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1835,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 172,
                            Force = 106,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 173,
                            Force = 746,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 174,
                            Force = 559,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1970,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1531,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 177,
                            Force = 1350,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 178,
                            Force = 781,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 179,
                            Force = 835,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 180,
                            Force = 393,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 181,
                            Force = 818,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1866,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 183,
                            Force = 1137,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 184,
                            Force = 352,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 185,
                            Force = 1347,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 186,
                            Force = 23,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 187,
                            Force = 21,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1416,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 189,
                            Force = 888,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 190,
                            Force = 972,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 191,
                            Force = 123,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 192,
                            Force = 1850,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 672,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 194,
                            Force = 974,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 195,
                            Force = 646,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 196,
                            Force = 149,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 197,
                            Force = 739,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1165,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 199,
                            Force = 1280,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 200,
                            Force = 416,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 201,
                            Force = 987,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 202,
                            Force = 889,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 203,
                            Force = 683,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 204,
                            Force = 494,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 205,
                            Force = 3,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1995,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 207,
                            Force = 893,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1484,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 209,
                            Force = 1389,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 210,
                            Force = 348,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 211,
                            Force = 754,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1913,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 213,
                            Force = 80,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 214,
                            Force = 106,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 215,
                            Force = 1688,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 216,
                            Force = 1798,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 217,
                            Force = 82,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 218,
                            Force = 48,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 219,
                            Force = 1261,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 220,
                            Force = 305,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 221,
                            Force = 380,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1281,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 223,
                            Force = 623,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 224,
                            Force = 579,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 225,
                            Force = 1075,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 226,
                            Force = 1524,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 227,
                            Force = 82,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 228,
                            Force = 97,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 229,
                            Force = 405,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1221,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 991,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 232,
                            Force = 408,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 233,
                            Force = 956,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1037,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 235,
                            Force = 1298,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 236,
                            Force = 1449,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1189,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1057,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1284,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 240,
                            Force = 392,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 241,
                            Force = 131,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 242,
                            Force = 689,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1920,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 244,
                            Force = 339,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1619,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 246,
                            Force = 61,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 247,
                            Force = 1172,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 248,
                            Force = 985,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1823,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 250,
                            Force = 1996,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1041,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 252,
                            Force = 1848,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1806,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 254,
                            Force = 352,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1137,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 256,
                            Force = 373,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1122,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1837,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 259,
                            Force = 775,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1382,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1983,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 262,
                            Force = 137,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 263,
                            Force = 282,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 264,
                            Force = 662,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 265,
                            Force = 1635,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 266,
                            Force = 378,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 267,
                            Force = 682,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 268,
                            Force = 941,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 269,
                            Force = 430,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1861,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1669,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1234,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 1981,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 274,
                            Force = 40,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1025,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1022,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1903,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 278,
                            Force = 463,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1115,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1621,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1237,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 282,
                            Force = 226,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 283,
                            Force = 993,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1295,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 285,
                            Force = 640,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 286,
                            Force = 562,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1597,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 288,
                            Force = 234,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 289,
                            Force = 1256,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 290,
                            Force = 878,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 291,
                            Force = 607,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 292,
                            Force = 1858,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 293,
                            Force = 28,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1440,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 295,
                            Force = 1390,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 296,
                            Force = 1690,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1267,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 1727,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 299,
                            Force = 60,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 442,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 301,
                            Force = 1886,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1432,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 303,
                            Force = 104,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 304,
                            Force = 347,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1666,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 306,
                            Force = 216,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 307,
                            Force = 1020,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 308,
                            Force = 937,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 309,
                            Force = 0,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 310,
                            Force = 1580,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 311,
                            Force = 790,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 312,
                            Force = 159,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 313,
                            Force = 405,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 1250,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 315,
                            Force = 820,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1806,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1345,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 1091,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 665,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 320,
                            Force = 1149,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 321,
                            Force = 1073,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 322,
                            Force = 538,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 323,
                            Force = 550,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 324,
                            Force = 1406,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 325,
                            Force = 1421,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 326,
                            Force = 1859,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 327,
                            Force = 414,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 328,
                            Force = 1418,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 329,
                            Force = 1034,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 330,
                            Force = 1889,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 331,
                            Force = 17,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 332,
                            Force = 1460,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 333,
                            Force = 118,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 334,
                            Force = 1871,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 335,
                            Force = 1578,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 336,
                            Force = 438,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 337,
                            Force = 866,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 338,
                            Force = 1696,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 339,
                            Force = 927,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 340,
                            Force = 1695,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 341,
                            Force = 1885,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 342,
                            Force = 458,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 343,
                            Force = 1200,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 344,
                            Force = 1453,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 345,
                            Force = 371,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 346,
                            Force = 593,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 347,
                            Force = 244,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 348,
                            Force = 504,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 349,
                            Force = 567,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 350,
                            Force = 48,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 351,
                            Force = 253,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 352,
                            Force = 353,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 353,
                            Force = 1246,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 354,
                            Force = 1871,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 355,
                            Force = 1148,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 356,
                            Force = 512,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 357,
                            Force = 1009,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 358,
                            Force = 163,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 359,
                            Force = 538,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 360,
                            Force = 1876,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 361,
                            Force = 1433,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 362,
                            Force = 1123,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 363,
                            Force = 1367,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 364,
                            Force = 216,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 365,
                            Force = 649,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 366,
                            Force = 1301,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 367,
                            Force = 1887,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 368,
                            Force = 402,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 369,
                            Force = 1567,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 370,
                            Force = 957,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 371,
                            Force = 1600,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 372,
                            Force = 869,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 373,
                            Force = 1733,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 374,
                            Force = 226,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 375,
                            Force = 696,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 376,
                            Force = 745,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 377,
                            Force = 1891,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 378,
                            Force = 866,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 379,
                            Force = 1225,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 380,
                            Force = 1394,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 381,
                            Force = 1518,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 382,
                            Force = 418,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 383,
                            Force = 887,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 384,
                            Force = 179,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 385,
                            Force = 1600,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 386,
                            Force = 1276,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 387,
                            Force = 121,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 388,
                            Force = 573,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 389,
                            Force = 336,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 390,
                            Force = 57,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 391,
                            Force = 1261,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 392,
                            Force = 634,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 393,
                            Force = 1361,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 394,
                            Force = 17,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 395,
                            Force = 974,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 396,
                            Force = 292,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 397,
                            Force = 762,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 398,
                            Force = 37,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 399,
                            Force = 639,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 400,
                            Force = 839,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 401,
                            Force = 1989,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 402,
                            Force = 1541,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 403,
                            Force = 95,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 404,
                            Force = 170,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 405,
                            Force = 1832,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 406,
                            Force = 685,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 407,
                            Force = 1703,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 408,
                            Force = 1214,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 409,
                            Force = 989,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 410,
                            Force = 333,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 411,
                            Force = 405,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 412,
                            Force = 1913,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 413,
                            Force = 1610,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 414,
                            Force = 636,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 415,
                            Force = 1295,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 416,
                            Force = 293,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 417,
                            Force = 988,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 418,
                            Force = 727,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 419,
                            Force = 1433,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.HasOne("BO.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("ArtsMartiauxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.Samourai", null)
                        .WithMany()
                        .HasForeignKey("SamouraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
